name: flutter_junitreport
version: 2.0.7-dev.1
description: Generate JUnit XML reports from dart test runs. Transforms the output of dart or flutter tests to
  JUnit style XML

homepage: https://github.com/waffiqaziz/flutter-junitreport
documentation:

environment:
  sdk: ^3.7.0

dependencies:
  args: ^2.7.0
  intl: ^0.20.2
  testreport: ^2.0.1
  xml: ^6.5.0

dev_dependencies:
  test: ^1.26.1
  lints: ^6.0.0

executables:
  tojunit:
